config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'contact', to: 'toppages#contact'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper

  private

    def require_user_logged_in
      unless logged_in?
        redirect_to login_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    #email = params[:session][:email].downcase
    #password = params[:session][:password]
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      flash[:success] = 'ログインに成功しました。'
      redirect_to user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    logout if logged_in?
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end

  private

    def login(email, password)
      @user = User.find_by(email: email)
      if @user && @user.authenticate(password)
        session[:user_id] = @user.id
        return true
      else
        return false
      end
    end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @users = current_user.followings & current_user.followers
    end
  end
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if(user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !!current_user
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def logout
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="headerNav">
  <div class="container">
    <div class="row headerNavBox">
      <a href="<%= root_path %>" class="col-xs-12 col-sm-3 headerNavBtn">
        トップページ
      </a>
      <div class="col-xs-12 col-sm-3 headerNavBtn" >
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">ユーザーを探す</a>
        <ul class="dropdown-menu dropdown-menu-right">
          <li class="dropdown-item"><%= link_to 'タグから探す', tags_path %></li>
          <li class="dropdown-item"><%= link_to 'つぶやきから探す', posts_path %></li>
        </ul>
      </div>
      <a href="<%= signup_path %>" class="col-xs-12 col-sm-3 headerNavBtn">
        新規登録
      </a>
      <a href="<%= login_path %>" class="col-xs-12 col-sm-3 headerNavBtn">
        ログイン
      </a>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Engineer Match</title>
    <%= csrf_meta_tags %>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <div class="container">

      <% if current_page?(root_path) || logged_in? && current_page?(followers_user_path(current_user)) %>
        <div class='top-wrapper'>
          <%#　<%= render 'layouts/header' %>
        </div>
      <% else %>
        <div class="nav">
          <%#<%= render 'layouts/header' %>
        </div>
      <% end %>
      <%#<%= render 'layouts/flash_messages' %>

      <%= yield %>

      <footer>
        <%#<a href="<%= contact_path %><%#" style="color: #FFF">お問い合わせ</a>
      </footer>

    </div>
  </body>
</html>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <div class='text-center'>
    <%= image_tag current_user.avatar, size: '75x75', class: 'avatar' if current_user.avatar.attached?%>
    <p style="color:#FFFFFF"><%= current_user.name %></p>
  </div>
<% else %>
  <div class="site-description text-center">
    <h3 style="font-size: 16px">エンジニアを目指す人のためのマッチングアプリ</h3>
    <p class='mt-5'>■ ■ ■このWEBサイトについて ■ ■ ■</p>
    <p>独学ではなかなか技術が身につかない...</p>
    <p>どこから取り組めばよいかわからない...</p>
    <p>他の人はどんな勉強法をしているのか参考にしたい...</p>
    <p class="mb-5">Engineer Matchでは、気になるエンジニアに気軽にメッセージを送れます。</p>
    <p class='mt-5'>■ ■ ■ テストログイン ■ ■ ■</p>
    <p>Email : test@test.com</p>
    <p>Password : password</p>
  </div>

  <a class="top-signup login", href="<%= login_path %>">Login</a>

  <div class='top' ontouchstart="">
    <div class="mask">
      <p class="caption text-center">いいね機能</p>
      <div class="caption text-center"><p>気になるユーザーをいいねしよう！<br>いいねが返ってきたらメッセージのやりとりができます</p></div>
    </div>
  </div>

  <div class=middle ontouchstart="">
    <div class="mask">
      <p class="caption text-center">ダイレクトメッセージ機能</p>
      <div class="caption text-center">気になるユーザーにメッセージを送ってみよう！<br>技術の話でも相談でも！</div>
    </div>
  </div>

  <div class='bottom' ontouchstart="">
    <div class="mask">
      <p class="caption text-center">タグ機能、つぶやき機能</p>
      <div class="caption text-center">自分の得意な技術のタグに参加したり、つぶやいてみよう！</br>タグやつぶやきから気になるユーザーを探せます</div>
    </div>
  </div>

<%#  <a class="top-signup signup", href="<%= signup_path %>">Sign up</a> %>

<%#  <p class="text-center">or</p>

  <a class="top-signup login", href="<%= login_path %>">Login</a>

<% end %>